#!/usr/bin/env node

/**
 * {{serverName}} — an MCP server generated by create-mcp-server.
 * Built from an OpenAPI spec: every API endpoint became one MCP tool.
 *
 * Transports:
 *   - stdio (default) — for local use and desktop clients.
 *   - Streamable HTTP — set MCP_TRANSPORT=http (and optional PORT) to run
 *     it as a remote server for hosted agents.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createServer as createHttpServer } from "node:http";
import { z } from "zod";

// The API this server talks to. You can override it with an env variable.
const BASE_URL = process.env.API_BASE_URL || "{{baseUrl}}";

// Optional outbound auth: if you set API_TOKEN, it is sent to the API as a
// Bearer token on every request.
const API_TOKEN = process.env.API_TOKEN;

// How long to wait for the API before giving up (milliseconds).
const REQUEST_TIMEOUT_MS = Number(process.env.REQUEST_TIMEOUT_MS) || 30000;

// How many times to retry a failed/5xx upstream request (after the first try).
const MAX_RETRIES = Number(process.env.MAX_RETRIES) || 2;

// --- HTTP transport settings (only used when MCP_TRANSPORT=http) ---
// Inbound auth: if set, clients must send `Authorization: Bearer <token>`.
const MCP_AUTH_TOKEN = process.env.MCP_AUTH_TOKEN;
// DNS-rebinding protection: if set (comma-separated), only these Host
// headers are allowed (e.g. "api.example.com,localhost:3000").
const ALLOWED_HOSTS = (process.env.ALLOWED_HOSTS ?? "")
  .split(",")
  .map((h) => h.trim())
  .filter(Boolean);

// One parameter of an endpoint.
type ApiParam = {
  name: string;
  in: "path" | "query";
  type: "string" | "number" | "boolean";
  description: string;
  required: boolean;
};

// One entry per API endpoint. The generator fills this in.
type Operation = {
  name: string;
  description: string;
  method: string;
  path: string;
  params: ApiParam[];
  hasBody: boolean;
};

const operations: Operation[] = {{operations}};

// Turn one parameter into a zod validator (the input's rules).
function buildField(param: ApiParam): z.ZodTypeAny {
  let field: z.ZodTypeAny =
    param.type === "number"
      ? z.number()
      : param.type === "boolean"
        ? z.boolean()
        : z.string();
  if (param.description) field = field.describe(param.description);
  if (!param.required) field = field.optional();
  return field;
}

// Fetch with a timeout, retrying transient failures (network errors and 5xx
// responses) with exponential backoff.
async function fetchWithRetry(url: URL, init: RequestInit): Promise<Response> {
  let lastError: unknown;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
    try {
      const response = await fetch(url, { ...init, signal: controller.signal });
      if (response.status < 500) return response; // success or client error
      lastError = new Error(`HTTP ${response.status}`);
      if (attempt === MAX_RETRIES) return response; // out of retries
    } catch (error) {
      lastError = error;
      if (attempt === MAX_RETRIES) throw error;
    } finally {
      clearTimeout(timer);
    }
    // Exponential backoff: 250ms, 500ms, 1000ms, ...
    await new Promise((resolve) => setTimeout(resolve, 250 * 2 ** attempt));
  }
  throw lastError;
}

// Build a fresh server with all tools registered. We make a NEW one per
// HTTP request (stateless mode), so this is a function rather than a global.
function createServer(): McpServer {
  const server = new McpServer({ name: "{{serverName}}", version: "0.1.0" });

  for (const op of operations) {
    // Build the tool's input schema from the endpoint's parameters.
    const inputSchema: Record<string, z.ZodTypeAny> = {};
    for (const param of op.params) inputSchema[param.name] = buildField(param);
    if (op.hasBody) {
      inputSchema["body"] = z
        .string()
        .describe("JSON request body, as a string")
        .optional();
    }

    server.registerTool(
      op.name,
      { description: op.description, inputSchema },
      async (args) => {
        const values = args as Record<string, unknown>;

        try {
          // 1. Fill path parameters into the URL, e.g. /pets/{petId}.
          let filledPath = op.path;
          for (const param of op.params) {
            if (param.in === "path" && values[param.name] !== undefined) {
              filledPath = filledPath.replace(
                `{${param.name}}`,
                encodeURIComponent(String(values[param.name]))
              );
            }
          }

          // 2. Add any query parameters that were provided.
          const url = new URL(BASE_URL + filledPath);
          for (const param of op.params) {
            if (param.in === "query" && values[param.name] !== undefined) {
              url.searchParams.set(param.name, String(values[param.name]));
            }
          }

          // 3. Build headers (and a body, if this endpoint takes one).
          const headers: Record<string, string> = {};
          if (API_TOKEN) headers["Authorization"] = `Bearer ${API_TOKEN}`;
          if (op.hasBody) headers["Content-Type"] = "application/json";

          // 4. Make the request (with timeout + retries on transient errors).
          const response = await fetchWithRetry(url, {
            method: op.method,
            headers,
            body: op.hasBody && values.body ? String(values.body) : undefined,
          });
          const text = await response.text();

          return {
            content: [
              { type: "text", text: `HTTP ${response.status}\n\n${text}` },
            ],
          };
        } catch (error) {
          // Network error, timeout, bad URL, etc. — report as a tool error.
          return {
            isError: true,
            content: [
              {
                type: "text",
                text: `Request to ${op.method} ${op.path} failed: ${
                  (error as Error).message
                }`,
              },
            ],
          };
        }
      }
    );
  }

  return server;
}

// Start over stdio (default) or Streamable HTTP (MCP_TRANSPORT=http).
async function main() {
  if (process.env.MCP_TRANSPORT === "http") {
    const port = Number(process.env.PORT) || 3000;

    const httpServer = createHttpServer(async (req, res) => {
      // Public health check for load balancers / orchestrators (no auth).
      if (req.method === "GET" && req.url === "/health") {
        res.statusCode = 200;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ status: "ok" }));
        return;
      }

      if (req.method === "POST" && req.url === "/mcp") {
        // Inbound auth: if MCP_AUTH_TOKEN is set, require a matching token.
        if (
          MCP_AUTH_TOKEN &&
          req.headers.authorization !== `Bearer ${MCP_AUTH_TOKEN}`
        ) {
          res.statusCode = 401;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ error: "Unauthorized" }));
          return;
        }

        // Stateless Streamable HTTP: one fresh server + transport per request.
        try {
          const chunks: Buffer[] = [];
          for await (const chunk of req) chunks.push(chunk as Buffer);
          const body = chunks.length
            ? JSON.parse(Buffer.concat(chunks).toString())
            : undefined;

          const server = createServer();
          const transport = new StreamableHTTPServerTransport({
            sessionIdGenerator: undefined,
            ...(ALLOWED_HOSTS.length > 0
              ? { enableDnsRebindingProtection: true, allowedHosts: ALLOWED_HOSTS }
              : {}),
          });
          res.on("close", () => {
            void transport.close();
            void server.close();
          });
          await server.connect(transport);
          await transport.handleRequest(req, res, body);
        } catch (error) {
          console.error("Request error:", error);
          if (!res.headersSent) {
            res.statusCode = 500;
            res.end();
          }
        }
        return;
      }

      res.statusCode = 405;
      res.end();
    });

    httpServer.listen(port, () => {
      console.error(
        `MCP server (HTTP) listening on http://localhost:${port}/mcp`
      );
    });

    // Graceful shutdown: stop accepting connections, then exit cleanly.
    const shutdown = () => {
      console.error("Shutting down...");
      httpServer.close(() => process.exit(0));
    };
    process.on("SIGTERM", shutdown);
    process.on("SIGINT", shutdown);
  } else {
    const server = createServer();
    await server.connect(new StdioServerTransport());
  }
}

main().catch((error) => {
  console.error("Server error:", error);
  process.exit(1);
});
