#!/usr/bin/env node

/**
 * {{serverName}} — an MCP server generated by create-mcp-server.
 * Built from an OpenAPI spec: every API endpoint became one MCP tool.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

// The API this server talks to. You can override it with an env variable.
const BASE_URL = process.env.API_BASE_URL || "{{baseUrl}}";

// Optional auth: if you set API_TOKEN, it is sent as a Bearer token.
const API_TOKEN = process.env.API_TOKEN;

// One entry per API endpoint. The generator fills this in.
type Operation = {
  name: string;
  description: string;
  method: string;
  path: string;
  pathParams: string[];
  queryParams: string[];
  hasBody: boolean;
};

const operations: Operation[] = {{operations}};

const server = new McpServer({ name: "{{serverName}}", version: "0.1.0" });

// Turn every endpoint into an MCP tool.
for (const op of operations) {
  // Build the tool's input schema from the endpoint's parameters.
  // Path params are required; query params and the body are optional.
  const inputSchema: Record<string, z.ZodTypeAny> = {};
  for (const p of op.pathParams) inputSchema[p] = z.string();
  for (const q of op.queryParams) inputSchema[q] = z.string().optional();
  if (op.hasBody) {
    inputSchema["body"] = z
      .string()
      .describe("JSON request body, as a string")
      .optional();
  }

  server.registerTool(
    op.name,
    { description: op.description, inputSchema },
    async (args) => {
      const values = args as Record<string, unknown>;

      // 1. Fill path parameters into the URL, e.g. /pets/{petId}.
      let filledPath = op.path;
      for (const p of op.pathParams) {
        filledPath = filledPath.replace(
          `{${p}}`,
          encodeURIComponent(String(values[p]))
        );
      }

      // 2. Add any query parameters that were provided.
      const url = new URL(BASE_URL + filledPath);
      for (const q of op.queryParams) {
        if (values[q] !== undefined) {
          url.searchParams.set(q, String(values[q]));
        }
      }

      // 3. Build headers (and a body, if this endpoint takes one).
      const headers: Record<string, string> = {};
      if (API_TOKEN) headers["Authorization"] = `Bearer ${API_TOKEN}`;
      if (op.hasBody) headers["Content-Type"] = "application/json";

      // 4. Make the request and return the response as text.
      const response = await fetch(url, {
        method: op.method,
        headers,
        body: op.hasBody && values.body ? String(values.body) : undefined,
      });
      const text = await response.text();

      return {
        content: [{ type: "text", text: `HTTP ${response.status}\n\n${text}` }],
      };
    }
  );
}

async function main() {
  await server.connect(new StdioServerTransport());
}

main().catch((error) => {
  console.error("Server error:", error);
  process.exit(1);
});
