"""
{{serverName}} — an MCP server generated by create-mcp-server.

This server exposes one example tool: {{toolName}}.
"""

from mcp.server.fastmcp import FastMCP

# Create the MCP server. The name is how clients (like Claude) identify it.
mcp = FastMCP("{{serverName}}")


# @mcp.tool() turns a normal Python function into an MCP tool.
#   - The type hints (name: str) become the tool's input schema automatically.
#   - The docstring becomes the tool's description shown to the AI.
@mcp.tool()
def {{toolName}}(name: str) -> str:
    """Say hello to the given name."""
    return f"Hello, {name}! This is the {{toolName}} tool from {{serverName}}."


if __name__ == "__main__":
    # Run the server over stdio (standard input/output) — the simplest
    # transport, and the one the MCP Inspector uses to connect.
    mcp.run()
