#!/usr/bin/env node

/**
 * {{serverName}} — an MCP server generated by create-mcp-server.
 * It exposes one example tool: {{toolName}}.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

// Create the MCP server. The name/version identify it to clients.
const server = new McpServer({
  name: "{{serverName}}",
  version: "0.1.0",
});

// Register one example tool.
//   1. the tool's name (what the AI calls)
//   2. its config: a description + an input schema (zod validates the input)
//   3. the function that runs when the tool is called
server.registerTool(
  "{{toolName}}",
  {
    title: "{{toolName}}",
    description: "Say hello to the given name.",
    inputSchema: { name: z.string() },
  },
  async ({ name }) => ({
    content: [
      {
        type: "text",
        text: `Hello, ${name}! This is the {{toolName}} tool from {{serverName}}.`,
      },
    ],
  })
);

// Connect the server to stdio (standard input/output) — the simplest
// transport, and the one the MCP Inspector uses to connect.
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

// If anything goes wrong, print the error and exit with a failure code.
main().catch((error) => {
  console.error("Server error:", error);
  process.exit(1);
});
